const mongoose = require('mongoose');
require('dotenv').config({ path: './backend/.env' });
const Doctor = require('./Doctor');

const doctors = [
  {
    name: "Dr. Suraja Nutalapati",
    title: "MD (General Medicine)",
    specialty: "General Physician | Internal Medicine Specialist",
    experience: 12,
    fees: 499,
    photo: "/doc1.webp",
    patients: 100,
    rating: 4.7,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: ["TOP CONSULTED DOCTOR"],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 88,
    patientCount: 100
  },
  {
    name: "Dr. Shaaham Simiish",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 6,
    fees: 399,
    photo: "/doc1.webp",
    patients: 75,
    rating: 4.5,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 91,
    patientCount: 75
  },
  {
    name: "Dr. J T Hema Pratima",
    title: "MBBS",
    specialty: "General Physician",
    experience: 16,
    fees: 499,
    photo: "/doc1.webp",
    patients: 120,
    rating: 4.8,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Tamil Nadu, Chennai",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 90,
    patientCount: 120
  },
  {
    name: "Dr. Mohammad Huzef Ul Arifeen",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 5,
    fees: 350,
    photo: "/doc1.webp",
    patients: 60,
    rating: 4.3,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 85,
    patientCount: 60
  },
  {
    name: "Dr. Visantharanee Nair",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 18,
    fees: 499,
    photo: "/doc1.webp",
    patients: 130,
    rating: 4.9,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Kerala, Angamaly",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 92,
    patientCount: 130
  },
  {
    name: "Dr. Siri Nallapu",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 5,
    fees: 399,
    photo: "/doc1.webp",
    patients: 70,
    rating: 4.4,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 87,
    patientCount: 70
  },
  {
    name: "Dr. Divya Lakha Gunta",
    title: "MBBS, MD (PATHOLOGY)",
    specialty: "General Practitioner",
    experience: 6,
    fees: 480,
    photo: "/doc1.webp",
    patients: 80,
    rating: 4.6,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Andhra Pradesh, Visakhapatnam",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 89,
    patientCount: 80
  },
  {
    name: "Dr. Immanul Raj P",
    title: "MBBS, MBBS (RMO)",
    specialty: "General Practitioner",
    experience: 8,
    fees: 450,
    photo: "/doc1.webp",
    patients: 90,
    rating: 4.5,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Tamil Nadu, Madurai",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 88,
    patientCount: 90
  },
  {
    name: "Dr. V. Jayaverndher R",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 15,
    fees: 499,
    photo: "/doc1.webp",
    patients: 110,
    rating: 4.7,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 90,
    patientCount: 110
  },
  {
    name: "Dr. Rebinipriyanka Reddy D",
    title: "MBBS",
    specialty: "General Practitioner",
    experience: 5,
    fees: 479,
    photo: "/doc1.webp",
    patients: 65,
    rating: 4.4,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo 247 Virtual Clinic - Telangana, Hyderabad",
    consultationModes: ["Online"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Consult Online",
    thumbsUpPercentage: 86,
    patientCount: 65
  },
  // Added doctors with Hospital Visit consultation mode
  {
    name: "Dr. Anil Kumar",
    title: "MD (General Medicine)",
    specialty: "General Physician",
    location: "Telangana, Hyderabad",
    experience: 10,
    fees: 600,
    photo: "/doc1.webp",
    patients: 150,
    rating: 4.6,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English", "Hindi"],
    facilityName: "Apollo Hospital - Telangana, Hyderabad",
    consultationModes: ["Hospital Visit"],
    badges: ["Experienced"],
    cashbackAmount: 0,
    availabilityText: "Visit Hospital",
    thumbsUpPercentage: 85,
    patientCount: 150
  },
  {
    name: "Dr. Meena Reddy",
    title: "MBBS",
    specialty: "General Practitioner",
    location: "Telangana, Hyderabad",
    experience: 7,
    fees: 550,
    photo: "/doc1.webp",
    patients: 90,
    rating: 4.4,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English", "Telugu"],
    facilityName: "Apollo Hospital - Telangana, Hyderabad",
    consultationModes: ["Hospital Visit"],
    badges: ["Trusted"],
    cashbackAmount: 0,
    availabilityText: "Visit Hospital",
    thumbsUpPercentage: 88,
    patientCount: 90
  },
  // New doctors added from user request
  {
    name: "Dr. Rajib Paul",
    title: "MBBS, MD (GEN. MED.)",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Hyderabad",
    experience: 20,
    fees: 1500,
    photo: "/doc1.webp",
    patients: 1325,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo Hospitals Jubilee Hills, Hyderabad",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 93,
    patientCount: 1325
  },
  {
    name: "Dr. Raza Shah",
    title: "MBBS, MD (GEN. MED.)",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Bengaluru",
    experience: 8,
    fees: 950,
    photo: "/doc1.webp",
    patients: 1125,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo Hospitals Bannerghatta Road, Bengaluru",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 89,
    patientCount: 1125
  },
  {
    name: "Dr. Ramesh B S",
    title: "MBBS, MD",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Bengaluru",
    experience: 36,
    fees: 950,
    photo: "/doc1.webp",
    patients: 0,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo Hospitals Bannerghatta Road, Bengaluru",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 0,
    patientCount: 0
  },
  {
    name: "Dr. Swarna Deepak K",
    title: "MBBS, MD (INTERNAL MEDICINE)",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Hyderabad",
    experience: 17,
    fees: 1000,
    photo: "/doc1.webp",
    patients: 1325,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo Hospitals Jubilee Hills, Hyderabad",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 82,
    patientCount: 1325
  },
  {
    name: "Dr. Vaishali Lokhande",
    title: "MBBS, DNB (INTERNAL MEDICINE)",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Mumbai",
    experience: 12,
    fees: 1700,
    photo: "/doc1.webp",
    patients: 125,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo Hospitals CBD Belapur, Mumbai",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 94,
    patientCount: 125
  },
  {
    name: "Dr. Anand Misra",
    title: "MBBS, MD",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Mumbai",
    experience: 8,
    fees: 950,
    photo: "/doc1.webp",
    patients: 0,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Male",
    languages: ["English"],
    facilityName: "Apollo Hospitals CBD Belapur, Mumbai",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 0,
    patientCount: 0
  },
  {
    name: "Dr. Hina Mehra",
    title: "MBBS, MD (MEDICINE)",
    specialty: "General Physician / Internal Medicine Specialist",
    location: "Bengaluru",
    experience: 8,
    fees: 950,
    photo: "/doc1.webp",
    patients: 175,
    rating: 0,
    availableTimings: ["Available Soon"],
    gender: "Female",
    languages: ["English"],
    facilityName: "Apollo Hospitals Bannerghatta Road, Bengaluru",
    consultationModes: ["Hospital Visit"],
    badges: [],
    cashbackAmount: 0,
    availabilityText: "Visit Doctor",
    thumbsUpPercentage: 96,
    patientCount: 175
  }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB connected for seeding');

    await Doctor.deleteMany({});
    console.log('Existing doctors removed');

    await Doctor.insertMany(doctors);
    console.log('Sample doctors inserted');

    mongoose.disconnect();
    console.log('MongoDB disconnected');
  } catch (error) {
    console.error('Error seeding doctors:', error);
  }
}

seed();
